name: SimpleMaterialGenerators
author: waleks, DragonDirt
description: 'Simple material generators for Slimefun with Networks support'
main: me.waleks.simplematerialgenerators.SimpleMaterialGenerators
website: https://github.com/waleks647/SMG
version: ${project.version}
api-version: '1.21'

depend:
  - Slimefun

softdepend:
  - Networks
